#!/bin/bash

sudo apt-get install bind9 dnsutils #Add utils to debug and trobleshoot

#As a caching server, uncomment and modify the "forwarders" section on /etc/bind/named.conf.options file
#with your ISP dns servers and/or your router one

sudo systemctl restart bind9.service #Restart dns service\

#Caching server done...

##To add the Primary Master functionality
#Edit /etc/bind/named.conf.local as:
#~ zone "str.edu" {
#~ 		type master;
#~	 	file "/etc/bind/db.str.edu";
#~ };
#
# Where db.str.edu will be generated by sudo cp /etc/bind/db.local /etc/bind/db.str.edu
#		if using ddns to update the resolver, then use instead var/lib/bind/db.str.edu


#Edit the db.str.edu file
##Check record types on section 8.4.1 of Ubuntu server guide 2016
#	Change the comment acording to the domain binded
#	In the SOA row, change "localhost." for the FQDN of your DNS server (ubuntu-server.str.edu.) and the root part for a valid email addr using "@" for "."(my_mail.str.edu.) don't forget the ending dot
#	In the NS row, change "localhost." for the FQDN of your DNS server (ubuntu-server.str.edu)
#	In the A row, change the loopback ip for the DNS server IP (10.0.10.1)
#	Add an A record, just after the Negative Cache TTL and befor the ";" (IN	A	10.0.10.1), NO "@" at row start
#	Add an NS record at the END (ns	IN	A	10.0.10.1), "ns" starts the row, instead of "@"
#	Ensure that ;Serial field is greater each time a modification is made in this file, recomended use a timestapformat
#			YYYYMMDDxx, where "xx" starts on 00, and increments on each mod of the current day

sudo systemctl restart bind9.service #Restart dns service\


###Adding a reverse zone file (addr to name)
#Edit /etc/bind/named.conf.local
#Add:
#~ zone "10.0.10.in-addr.arpa" {
	#~ type master;
	#~ file "/etc/bind/db.10";
#~ };
#NOTE: in the zone"... part, the ip is in reverse order, a 192 C type, would look like 1.168.192
#and the file would be db.192

sudo cp /etc/bind/db.127 /etc/bind/db.10

#Edit that zone file as the db.str.edu file
#Remember that MUST be ONE STR register pero each A register in db.str.edu
